### ISSUE TITLE
No issues... just sharing some stuff

### ISSUE THREAD

**Issue by JonHerke-TG** [karol-brejna-i/tigergraph-restpp-api#2]
Awesome Project! This might also be a helpful resource... maybe a bit out of date missing a few things. You can use something like this https://apitransform.com/how-to-convert-postman-collection-to-openapi/

https://documenter.getpostman.com/view/10822498/Szmh3wsw

**Comment by karol-brejna-i** [comment]
:-) Thanks. I started documenting the API from `/query` endpoint as most used by me for now. Soon, other endpoints will be defined and tested.
